name: Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ '**', '!gh-pages', '!coverage' ]
    types: [ opened, reopened, ready_for_review, synchronize ]
  workflow_call:
    inputs:
      ref:
        description: Reference to use for checking out
        default: ${{ github.sha }}
        type: string
    
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone recurse submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
    - name: Make
      working-directory: build
      run: ninja
    - name: Test
      working-directory: build/tests
      run: ctest
